### ISSUE TITLE
FR: Add link to ProfileManifests & Jamf-Custom-Profile-Schemas/ProfileManifestsMirror for helping other MacAdmins

### ISSUE THREAD

**Issue by apizz** [BIG-RAT/Managed-App-Schema-Builder#5]
I just recently stumbled across this project.  I don't expect a change to result by filing this issue, but I wanted to at least put in the request.

Part of what makes the MacAdmin community great is everyone's willingness to share and contribute to larger projects that we all then use.  This way when someone notices an issue or adds a feature everyone benefits.

When the JSON Schema was added to Jamf, I quickly saw the potential benefit of having a shared repo that all admins could utilize for taking non-native applications and management preferences in Jamf.  However, as is evident from the https://github.com/Jamf-Custom-Profile-Schemas org, this has resulted in a bunch of fragments with no central "owner" or single source of truth that represents all that's capable of being managed for a given app / domain.  I 100% see the value in this project as a tool, but I wonder if in addition the README might offer admins to explore other related projects which do provide a more centralized source of truth for all that can be managed and which all admins can immediately contribute to & benefit from.

I had envisioned taking the strong foundation that we'd built in https://github.com/ProfileCreator/ProfileManifests for defining the available applications and preferences that can be managed via configuration profile and bring that into the Jamf Schema format.  This very recently happened with https://github.com/Jamf-Custom-Profile-Schemas/ProfileManifestsMirror.  The ProfileManifests repo is what powers https://github.com/ProfileCreator/ProfileCreator as well as https://imazing.com/profile-editor, and any changes which are made in ProfileManifests are automatically replicated and processed in the Jamf Schema format in the linked repo.  The more admins that use these shared tools that build on each other's work and contributions, rather than duplicating them in different repos, I think we all serve to benefit.

My request then is to add a reference in the README to the shared work of both https://github.com/ProfileCreator/ProfileManifests & https://github.com/Jamf-Custom-Profile-Schemas/ProfileManifestsMirror to get admins contributing there, rather than defaulting to building their own isolated schemas.

Thank you for the consideration.

**Comment by BIG-RAT** [comment]
I like it - done.

**Comment by apizz** [comment]
Thanks so much!
